### PR TITLE
Fix subpaths in iteration.

### LINKED ISSUE #37: Daytona fails to read secrets if there are subpaths
Daytona fails to ignore subpaths when it's reading through the secrets in a specified path using `VAULT_SECRETS_FOO=secrets/foo`.

Assume a path `secrets/foo` that has a subpath `bar/`:
```
% vault list secrets/foo
Keys
----
bar/
foo1
foo2

% vault list secrets/foo/bar
Keys
----
bar1
bar2
```
This will cause Daytona to fail with:
```
DAYTONA - 2020/03/24 22:50:11 Starting v1.1.0...
DAYTONA - 2020/03/24 22:50:11 Attempting to automatically infer some k8s configuration data
DAYTONA - 2020/03/24 22:50:11 Checking for an existing, valid vault token
DAYTONA - 2020/03/24 22:50:11 No token found in VAULT_TOKEN env, checking path
DAYTONA - 2020/03/24 22:50:11 Found an existing token at /home/vault/.vault-token
DAYTONA - 2020/03/24 22:50:11 Starting secret fetch
DAYTONA - 2020/03/24 22:50:11 Starting iteration on secrets/foo
DAYTONA - 2020/03/24 22:50:11 Vault listed a secret 'bar', but got not-found trying to read it at 'secrets/foo/bar'; very strange
```

I would like to suggest  fixing this by ignoring/printing a warning if Daytona encounters a subpath instead of a key/value pair in the path it's iterating on.

### PR DESCRIPTION
**Pull request by robison**
Resolves #37

### CODE REVIEW

File: pkg/secrets/secrets.go [hunk 1]
```diff
@@ -246,7 +246,11 @@ func (sd *SecretDefinition) Walk(client *api.Client) error {
 		if !ok {
 			return fmt.Errorf("non-string secret name: %#v", key)
 		}
-		paths = append(paths, path.Join(sd.secretApex, key))
+		if !strings.HasSuffix(key, "/") {
+			paths = append(paths, path.Join(sd.secretApex, key))
+		} else {
+			log.Printf("Found subpath %s - not iterating!\n", key)
```
Comment (broamski) [inline pkg/secrets/secrets.go]: Can we make this commend a little more verbose. Maybe something like:

`"Found subpath %s while walking %s, only top-level path iteration is supported at this time", key, sd.secretApex`

Comment (robison) [reply pkg/secrets/secrets.go]: Done.
